"""initial canonical schema

Revision ID: 809125e61af1
Revises:
Create Date: 2026-08-04 23:49:47.607861
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "809125e61af1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "build_plates",
        sa.Column("plate_code", sa.String(length=2), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("klipper_mesh_profile", sa.String(length=120), nullable=False),
        sa.Column("surface_type", sa.String(length=120), nullable=True),
        sa.Column("manufacturer", sa.String(length=120), nullable=True),
        sa.Column("dimensions_mm", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "condition",
            sa.Enum("NEW", "GOOD", "WORN", "DAMAGED", "RETIRED", name="plate_condition"),
            nullable=False,
        ),
        sa.Column("status", sa.Enum("ACTIVE", "MAINTENANCE", "RETIRED", name="plate_status"), nullable=False),
        sa.Column("preferred_materials", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("max_bed_temp_c", sa.Numeric(precision=12, scale=5), nullable=True),
        sa.Column("last_cleaned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_mesh_calibrated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("record_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_build_plates")),
        sa.UniqueConstraint("plate_code", name=op.f("uq_build_plates_plate_code")),
    )
    op.create_table(
        "devices",
        sa.Column("device_code", sa.String(length=96), nullable=False),
        sa.Column("device_type", sa.String(length=32), nullable=False),
        sa.Column("credential_hash", sa.String(length=64), nullable=False),
        sa.Column("location", sa.String(length=160), nullable=True),
        sa.Column("firmware_version", sa.String(length=96), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_sequence", sa.Integer(), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_devices")),
        sa.UniqueConstraint("device_code", name=op.f("uq_devices_device_code")),
    )
    op.create_table(
        "outbox_jobs",
        sa.Column("job_type", sa.String(length=96), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("aggregate_type", sa.String(length=64), nullable=False),
        sa.Column("aggregate_id", sa.Uuid(), nullable=False),
        sa.Column("aggregate_version", sa.Integer(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "RUNNING", "COMPLETED", "FAILED", "DEAD", name="job_status"),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("locked_by", sa.String(length=128), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_class", sa.String(length=160), nullable=True),
        sa.Column("last_error_message", sa.String(length=500), nullable=True),
        sa.Column("remote_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_jobs")),
        sa.UniqueConstraint("job_type", "idempotency_key", name="uq_outbox_type_key"),
    )
    op.create_index(
        "ix_outbox_claim", "outbox_jobs", ["status", "next_attempt_at", "created_at"], unique=False
    )
    op.create_table(
        "projection_states",
        sa.Column("system", sa.String(length=32), nullable=False),
        sa.Column("object_type", sa.String(length=64), nullable=False),
        sa.Column("object_id", sa.Uuid(), nullable=False),
        sa.Column("remote_id", sa.String(length=160), nullable=True),
        sa.Column("remote_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("acknowledged_version", sa.Integer(), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projection_states")),
        sa.UniqueConstraint("system", "object_type", "object_id", name="uq_projection_object"),
    )
    op.create_table(
        "users",
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("normalized_username", sa.String(length=80), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column("role", sa.Enum("ADMINISTRATOR", "OPERATOR", "VIEWER", name="user_role"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("failed_login_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("record_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("normalized_username", name=op.f("uq_users_normalized_username")),
    )
    op.create_table(
        "vendors",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("preferred", sa.Boolean(), nullable=False),
        sa.Column("aliases", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("record_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendors")),
        sa.UniqueConstraint("name", name=op.f("uq_vendors_name")),
    )
    op.create_table(
        "audit_events",
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("source", sa.String(length=48), nullable=False),
        sa.Column("action", sa.String(length=96), nullable=False),
        sa.Column("object_type", sa.String(length=64), nullable=False),
        sa.Column("object_id", sa.Uuid(), nullable=True),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("correlation_id", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], name=op.f("fk_audit_events_actor_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(op.f("ix_audit_events_correlation_id"), "audit_events", ["correlation_id"], unique=False)
    op.create_index(
        "ix_audit_object_time", "audit_events", ["object_type", "object_id", "occurred_at"], unique=False
    )
    op.create_table(
        "filament_products",
        sa.Column("vendor_id", sa.UUID(), nullable=True),
        sa.Column("material_type", sa.String(length=48), nullable=False),
        sa.Column("filler", sa.String(length=96), nullable=True),
        sa.Column("finish", sa.String(length=96), nullable=True),
        sa.Column("color_name", sa.String(length=96), nullable=False),
        sa.Column("color_hex", sa.String(length=6), nullable=True),
        sa.Column("product_name", sa.String(length=160), nullable=True),
        sa.Column("diameter_mm", sa.Numeric(precision=12, scale=5), nullable=False),
        sa.Column("tolerance_mm", sa.Numeric(precision=12, scale=5), nullable=True),
        sa.Column("density_g_cm3", sa.Numeric(precision=12, scale=5), nullable=False),
        sa.Column("nominal_net_mass_g", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("record_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("density_g_cm3 > 0", name=op.f("ck_filament_products_density_positive")),
        sa.CheckConstraint("diameter_mm > 0", name=op.f("ck_filament_products_diameter_positive")),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_filament_products_vendor_id_vendors"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_filament_products")),
        sa.UniqueConstraint(
            "vendor_id",
            "material_type",
            "product_name",
            "color_name",
            "diameter_mm",
            name="uq_filament_product_identity",
        ),
    )
    op.create_index(
        op.f("ix_filament_products_material_type"), "filament_products", ["material_type"], unique=False
    )
    op.create_table(
        "import_runs",
        sa.Column("source_name", sa.String(length=256), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column("dry_run", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("report", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["approved_by"], ["users.id"], name=op.f("fk_import_runs_approved_by_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_runs")),
    )
    op.create_table(
        "printers",
        sa.Column("printer_code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("moonraker_base_url", sa.String(length=512), nullable=False),
        sa.Column("nozzle_diameter_mm", sa.Numeric(precision=12, scale=5), nullable=False),
        sa.Column("build_volume", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("active_plate_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("record_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["active_plate_id"], ["build_plates.id"], name=op.f("fk_printers_active_plate_id_build_plates")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_printers")),
        sa.UniqueConstraint("printer_code", name=op.f("uq_printers_printer_code")),
    )
    op.create_table(
        "user_sessions",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("idle_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_agent", sa.String(length=256), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_user_sessions_token_hash")),
    )
    op.create_index(
        "ix_user_sessions_expiry", "user_sessions", ["expires_at", "idle_expires_at"], unique=False
    )
    op.create_index(op.f("ix_user_sessions_user_id"), "user_sessions", ["user_id"], unique=False)
    op.create_table(
        "material_profiles",
        sa.Column("filament_product_id", sa.UUID(), nullable=False),
        sa.Column("printer_id", sa.UUID(), nullable=False),
        sa.Column("nozzle_diameter_mm", sa.Numeric(precision=12, scale=5), nullable=False),
        sa.Column("min_layer_height_mm", sa.Numeric(precision=12, scale=5), nullable=True),
        sa.Column("max_layer_height_mm", sa.Numeric(precision=12, scale=5), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "CALIBRATION_IN_PROGRESS",
                "VALIDATED",
                "PUBLISHED",
                "SUPERSEDED",
                "ARCHIVED",
                name="profile_status",
            ),
            nullable=False,
        ),
        sa.Column("chamber_temp_c", sa.Numeric(precision=12, scale=5), nullable=True),
        sa.Column("extruder_temp_c", sa.Numeric(precision=12, scale=5), nullable=False),
        sa.Column("bed_temp_c", sa.Numeric(precision=12, scale=5), nullable=False),
        sa.Column("flow_percent", sa.Numeric(precision=12, scale=5), nullable=False),
        sa.Column("print_speed_mm_s", sa.Numeric(precision=12, scale=5), nullable=True),
        sa.Column("outer_wall_speed_mm_s", sa.Numeric(precision=12, scale=5), nullable=True),
        sa.Column("inner_wall_speed_mm_s", sa.Numeric(precision=12, scale=5), nullable=True),
        sa.Column("infill_speed_mm_s", sa.Numeric(precision=12, scale=5), nullable=True),
        sa.Column("top_bottom_speed_mm_s", sa.Numeric(precision=12, scale=5), nullable=True),
        sa.Column("initial_layer_speed_mm_s", sa.Numeric(precision=12, scale=5), nullable=True),
        sa.Column("travel_speed_mm_s", sa.Numeric(precision=12, scale=5), nullable=True),
        sa.Column("support_speed_mm_s", sa.Numeric(precision=12, scale=5), nullable=True),
        sa.Column("bridge_speed_mm_s", sa.Numeric(precision=12, scale=5), nullable=True),
        sa.Column("retraction_distance_mm", sa.Numeric(precision=12, scale=5), nullable=True),
        sa.Column("retraction_speed_mm_s", sa.Numeric(precision=12, scale=5), nullable=True),
        sa.Column("cooling_enabled", sa.Boolean(), nullable=False),
        sa.Column("cooling_min_percent", sa.Numeric(precision=12, scale=5), nullable=False),
        sa.Column("cooling_max_percent", sa.Numeric(precision=12, scale=5), nullable=False),
        sa.Column("support_overhang_angle_deg", sa.Numeric(precision=12, scale=5), nullable=True),
        sa.Column("tree_max_branch_angle_deg", sa.Numeric(precision=12, scale=5), nullable=True),
        sa.Column("pressure_advance", sa.Numeric(precision=12, scale=5), nullable=True),
        sa.Column("filament_density_g_cm3", sa.Numeric(precision=12, scale=5), nullable=False),
        sa.Column("preferred_build_plate_id", sa.UUID(), nullable=True),
        sa.Column("ironing_enabled", sa.Boolean(), nullable=True),
        sa.Column("ironing_flow_percent", sa.Numeric(precision=12, scale=5), nullable=True),
        sa.Column("ironing_speed_mm_s", sa.Numeric(precision=12, scale=5), nullable=True),
        sa.Column("ironing_line_spacing_mm", sa.Numeric(precision=12, scale=5), nullable=True),
        sa.Column("cura_extensions_schema_version", sa.Integer(), nullable=False),
        sa.Column("cura_extensions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("record_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["filament_product_id"],
            ["filament_products.id"],
            name=op.f("fk_material_profiles_filament_product_id_filament_products"),
        ),
        sa.ForeignKeyConstraint(
            ["preferred_build_plate_id"],
            ["build_plates.id"],
            name=op.f("fk_material_profiles_preferred_build_plate_id_build_plates"),
        ),
        sa.ForeignKeyConstraint(
            ["printer_id"], ["printers.id"], name=op.f("fk_material_profiles_printer_id_printers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_material_profiles")),
        sa.UniqueConstraint(
            "filament_product_id",
            "printer_id",
            "nozzle_diameter_mm",
            "version",
            name="uq_material_profile_version",
        ),
    )
    op.create_table(
        "spools",
        sa.Column("spool_code", sa.String(length=64), nullable=False),
        sa.Column("filament_product_id", sa.UUID(), nullable=False),
        sa.Column("nominal_net_mass_g", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("tare_mass_g", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("remaining_mass_expected_g", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("remaining_mass_measured_g", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("remaining_mass_effective_g", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("weight_confidence", sa.String(length=32), nullable=False),
        sa.Column(
            "status",
            sa.Enum("NEEDS_WEIGHING", "IN_STOCK", "LOW", "EMPTY", "ARCHIVED", name="spool_status"),
            nullable=False,
        ),
        sa.Column("purchase_source", sa.String(length=160), nullable=True),
        sa.Column("purchase_date", sa.Date(), nullable=True),
        sa.Column("purchase_cost", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("first_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_measurement_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_usage_event_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("location", sa.String(length=160), nullable=True),
        sa.Column("active_printer_id", sa.UUID(), nullable=True),
        sa.Column("spoolman_id", sa.Integer(), nullable=True),
        sa.Column("label_path", sa.String(length=512), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("record_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("nominal_net_mass_g > 0", name=op.f("ck_spools_nominal_mass_positive")),
        sa.CheckConstraint("remaining_mass_effective_g >= 0", name=op.f("ck_spools_remaining_nonnegative")),
        sa.CheckConstraint("tare_mass_g >= 0", name=op.f("ck_spools_tare_nonnegative")),
        sa.ForeignKeyConstraint(
            ["active_printer_id"], ["printers.id"], name=op.f("fk_spools_active_printer_id_printers")
        ),
        sa.ForeignKeyConstraint(
            ["filament_product_id"],
            ["filament_products.id"],
            name=op.f("fk_spools_filament_product_id_filament_products"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_spools")),
        sa.UniqueConstraint("spool_code", name=op.f("uq_spools_spool_code")),
        sa.UniqueConstraint("spoolman_id", name=op.f("uq_spools_spoolman_id")),
    )
    op.create_index(op.f("ix_spools_filament_product_id"), "spools", ["filament_product_id"], unique=False)
    op.create_index("ix_spools_status_archived", "spools", ["status", "archived"], unique=False)
    op.create_table(
        "calibration_sessions",
        sa.Column("filament_product_id", sa.UUID(), nullable=False),
        sa.Column("spool_id", sa.UUID(), nullable=True),
        sa.Column("printer_id", sa.UUID(), nullable=False),
        sa.Column("nozzle_diameter_mm", sa.Numeric(precision=12, scale=5), nullable=False),
        sa.Column("build_plate_id", sa.UUID(), nullable=True),
        sa.Column("baseline_profile_id", sa.UUID(), nullable=True),
        sa.Column("published_profile_id", sa.UUID(), nullable=True),
        sa.Column("target_layer_height_mm", sa.Numeric(precision=12, scale=5), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "IN_PROGRESS",
                "READY_TO_PUBLISH",
                "PUBLISHED",
                "CANCELLED",
                name="calibration_status",
            ),
            nullable=False,
        ),
        sa.Column("operator_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("override_reason", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("record_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["baseline_profile_id"],
            ["material_profiles.id"],
            name=op.f("fk_calibration_sessions_baseline_profile_id_material_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["build_plate_id"],
            ["build_plates.id"],
            name=op.f("fk_calibration_sessions_build_plate_id_build_plates"),
        ),
        sa.ForeignKeyConstraint(
            ["filament_product_id"],
            ["filament_products.id"],
            name=op.f("fk_calibration_sessions_filament_product_id_filament_products"),
        ),
        sa.ForeignKeyConstraint(
            ["operator_id"], ["users.id"], name=op.f("fk_calibration_sessions_operator_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["printer_id"], ["printers.id"], name=op.f("fk_calibration_sessions_printer_id_printers")
        ),
        sa.ForeignKeyConstraint(
            ["published_profile_id"],
            ["material_profiles.id"],
            name=op.f("fk_calibration_sessions_published_profile_id_material_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["spool_id"], ["spools.id"], name=op.f("fk_calibration_sessions_spool_id_spools")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calibration_sessions")),
    )
    op.create_table(
        "nfc_tags",
        sa.Column("tag_uid_hash", sa.String(length=64), nullable=False),
        sa.Column("spool_id", sa.UUID(), nullable=False),
        sa.Column("technology", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["spool_id"], ["spools.id"], name=op.f("fk_nfc_tags_spool_id_spools")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nfc_tags")),
        sa.UniqueConstraint("tag_uid_hash", name=op.f("uq_nfc_tags_tag_uid_hash")),
    )
    op.create_table(
        "spool_measurements",
        sa.Column("spool_id", sa.UUID(), nullable=False),
        sa.Column(
            "source",
            sa.Enum("MANUAL", "SCALE", "IMPORT", "CORRECTION", name="measurement_source"),
            nullable=False,
        ),
        sa.Column("status", sa.Enum("ACCEPTED", "REJECTED", name="measurement_status"), nullable=False),
        sa.Column("gross_mass_g", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("tare_mass_g", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("net_mass_g", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("expected_before_g", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("variance_g", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("uncertainty_g", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("confidence", sa.String(length=32), nullable=False),
        sa.Column("requires_confirmation", sa.Boolean(), nullable=False),
        sa.Column("confirmed", sa.Boolean(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=True),
        sa.Column("device_sequence", sa.Integer(), nullable=True),
        sa.Column("operator_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("rejection_reason", sa.String(length=256), nullable=True),
        sa.Column("measured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint("gross_mass_g >= 0", name=op.f("ck_spool_measurements_gross_nonnegative")),
        sa.CheckConstraint(
            "tare_mass_g >= 0", name=op.f("ck_spool_measurements_measurement_tare_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["device_id"], ["devices.id"], name=op.f("fk_spool_measurements_device_id_devices")
        ),
        sa.ForeignKeyConstraint(
            ["operator_id"], ["users.id"], name=op.f("fk_spool_measurements_operator_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["spool_id"],
            ["spools.id"],
            name=op.f("fk_spool_measurements_spool_id_spools"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_spool_measurements")),
        sa.UniqueConstraint("spool_id", "idempotency_key", name="uq_measurement_idempotency"),
    )
    op.create_index(
        "ix_measurements_spool_time", "spool_measurements", ["spool_id", "measured_at"], unique=False
    )
    op.create_table(
        "spool_usage_events",
        sa.Column("spool_id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("printer_id", sa.UUID(), nullable=True),
        sa.Column("print_job_id", sa.String(length=160), nullable=True),
        sa.Column("mass_delta_g", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["printer_id"], ["printers.id"], name=op.f("fk_spool_usage_events_printer_id_printers")
        ),
        sa.ForeignKeyConstraint(
            ["spool_id"], ["spools.id"], name=op.f("fk_spool_usage_events_spool_id_spools")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_spool_usage_events")),
        sa.UniqueConstraint("source", "idempotency_key", name="uq_usage_source_key"),
    )
    op.create_index(op.f("ix_spool_usage_events_spool_id"), "spool_usage_events", ["spool_id"], unique=False)
    op.create_table(
        "calibration_steps",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("step_order", sa.Integer(), nullable=False),
        sa.Column("step_key", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NOT_STARTED",
                "IN_PROGRESS",
                "COMPLETED",
                "NEEDS_REVIEW",
                "SKIPPED",
                name="calibration_step_status",
            ),
            nullable=False,
        ),
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("artifact", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("affected_profile_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("record_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["calibration_sessions.id"],
            name=op.f("fk_calibration_steps_session_id_calibration_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calibration_steps")),
        sa.UniqueConstraint("session_id", "step_key", name="uq_calibration_step_key"),
        sa.UniqueConstraint("session_id", "step_order", name="uq_calibration_step_order"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("calibration_steps")
    op.drop_index(op.f("ix_spool_usage_events_spool_id"), table_name="spool_usage_events")
    op.drop_table("spool_usage_events")
    op.drop_index("ix_measurements_spool_time", table_name="spool_measurements")
    op.drop_table("spool_measurements")
    op.drop_table("nfc_tags")
    op.drop_table("calibration_sessions")
    op.drop_index("ix_spools_status_archived", table_name="spools")
    op.drop_index(op.f("ix_spools_filament_product_id"), table_name="spools")
    op.drop_table("spools")
    op.drop_table("material_profiles")
    op.drop_index(op.f("ix_user_sessions_user_id"), table_name="user_sessions")
    op.drop_index("ix_user_sessions_expiry", table_name="user_sessions")
    op.drop_table("user_sessions")
    op.drop_table("printers")
    op.drop_table("import_runs")
    op.drop_index(op.f("ix_filament_products_material_type"), table_name="filament_products")
    op.drop_table("filament_products")
    op.drop_index("ix_audit_object_time", table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_correlation_id"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_table("vendors")
    op.drop_table("users")
    op.drop_table("projection_states")
    op.drop_index("ix_outbox_claim", table_name="outbox_jobs")
    op.drop_table("outbox_jobs")
    op.drop_table("devices")
    op.drop_table("build_plates")
    bind = op.get_bind()
    for enum_name in (
        "calibration_step_status",
        "measurement_status",
        "measurement_source",
        "calibration_status",
        "spool_status",
        "profile_status",
        "user_role",
        "job_status",
        "plate_status",
        "plate_condition",
    ):
        postgresql.ENUM(name=enum_name).drop(bind, checkfirst=True)
    # ### end Alembic commands ###
