"""Import all models so Alembic can discover the complete metadata."""

from .auth import User, UserSession
from .base import Base
from .calibration import CalibrationSession, CalibrationStep
from .inventory import (
    BuildPlate,
    BuildPlateSurface,
    FilamentColor,
    FilamentProduct,
    MaterialProfile,
    MaterialTemplate,
    MaterialTemplateRevision,
    Nozzle,
    Printer,
    Spool,
    SpoolMeasurement,
    SpoolUsageEvent,
    Vendor,
)
from .operations import (
    ApplicationSetting,
    AuditEvent,
    BuildPlateMaintenanceEvent,
    Device,
    DiagnosticRun,
    ImportRun,
    NfcTag,
    Notification,
    NozzleLifecycleEvent,
    OutboxJob,
    ProjectionState,
    UserNotificationState,
    WorkerHeartbeat,
)
from .printing import PrintAssessment, PrintJob, PrintMaterialSegment
from .workstations import (
    CuraDeployment,
    CuraManagedEditReceipt,
    CuraRecoveryRestore,
    CuraRecoverySnapshot,
    CuraTakeoverMapping,
    WorkstationAgent,
    WorkstationPairingCode,
)

__all__ = [
    "ApplicationSetting",
    "AuditEvent",
    "Base",
    "BuildPlate",
    "BuildPlateMaintenanceEvent",
    "BuildPlateSurface",
    "CalibrationSession",
    "CalibrationStep",
    "CuraDeployment",
    "CuraManagedEditReceipt",
    "CuraRecoveryRestore",
    "CuraRecoverySnapshot",
    "CuraTakeoverMapping",
    "Device",
    "DiagnosticRun",
    "FilamentColor",
    "FilamentProduct",
    "ImportRun",
    "MaterialProfile",
    "MaterialTemplate",
    "MaterialTemplateRevision",
    "NfcTag",
    "Notification",
    "Nozzle",
    "NozzleLifecycleEvent",
    "OutboxJob",
    "PrintAssessment",
    "PrintJob",
    "PrintMaterialSegment",
    "Printer",
    "ProjectionState",
    "Spool",
    "SpoolMeasurement",
    "SpoolUsageEvent",
    "User",
    "UserNotificationState",
    "UserSession",
    "Vendor",
    "WorkerHeartbeat",
    "WorkstationAgent",
    "WorkstationPairingCode",
]
